export const IMAGES = {
    home: require("@/assets/tab-icons/home.png"),
    heart: require("@/assets/tab-icons/heart2.png"),
    like: require("@/assets/tab-icons/like.png"),
    restaurant: require("@/assets/tab-icons/restaurant.png"),
    street_food: require("@/assets/tab-icons/street-food.png"),
    user: require("@/assets/tab-icons/user.png"),
    user2: require("@/assets/tab-icons/user2.png"),
    plate: require("@/assets/tab-icons/plate-icon.png"),
    earth: require("@/assets/tab-icons/earth-icon.png"),
    traveler_icon: require("@/assets/tab-icons/traveler-icon.png"),
    button_heart_icon: require("@/assets/card-action-button-icons/button-heart-icon.png"),
    button_dislike: require("@/assets/card-action-button-icons/red-x.png"),
    button_info: require("@/assets/card-action-button-icons/question-mark.png"),
    no_image_found: require("@/assets/fallback/image-not-found.png"),
    nope_overlay: require("@/assets/overlay-icons/nope2.png"),
    like_overlay: require("@/assets/overlay-icons/like4.png"),
    info_overlay: require("@/assets/overlay-icons/thinking.png"),
    auth_bg: require("@/assets/images/signup-bg.png"),
    forked_logo: require("@/assets/images/forked-icon.png"),
} as const;